### ISSUE TITLE
Mejora de la parametrización

### ISSUE THREAD

**Issue by cr0hn** [lolcathost/enitsda#4]
Sería deseable que la interfaz de entrada sea parametrizable, no prefijada en el código

<img width="836" alt="enitsda_enitsda_deauth_py_at_master_ _lolcathost_enitsda" src="https://user-images.githubusercontent.com/4076390/49291032-0c6e3680-f4a9-11e8-88c0-9a7648cdf283.png">

**Comment by dsecuma** [comment]
Esta modificado
