### ISSUE TITLE
Certificado root en Github!!

### ISSUE THREAD

**Issue by cr0hn** [lolcathost/enitsda#5]
<img width="639" alt="enitsda_code_esp32_main_at_master_ _lolcathost_enitsda" src="https://user-images.githubusercontent.com/4076390/49292254-0e39f900-f4ad-11e8-9622-174b054cb8fc.png">

**Comment by jpsminix** [comment]
Buenos días,

Es la clave publica del CA del servidor.

Gracias.

**Comment by jpsminix** [comment]
Reabro el issue para el jurado.

**Comment by cr0hn** [comment]
Oks. No tengáis miedo en cerrar issues si no lo son
