### ISSUE TITLE
Django funcionando en modo Debug

### ISSUE THREAD

**Issue by cr0hn** [lolcathost/enitsda#7]
El modo DEBUG de Django está activado en código. Debería de ejecutarse en modo debug=0 en producción y, además, ser parametrizable (vía variable de entorno, fichero de configuración...)

<img width="766" alt="enitsda_settings_py_at_master_ _lolcathost_enitsda" src="https://user-images.githubusercontent.com/4076390/49292594-fe6ee480-f4ad-11e8-918b-67d042a07276.png">

**Comment by dsecuma** [comment]
Subido con cambios
