### ISSUE TITLE
Estático servidos por Django

### ISSUE THREAD

**Issue by cr0hn** [lolcathost/enitsda#8]
Los ficheros estáticos solo deberían ser servidos por Django cuando éste está en modo DEBUG. 

Esta entrada debería de estar parametrizada, condicionada a que solo se añadieran dichas rutas en modo DEBUG=1

<img width="731" alt="enitsda_urls_py_at_master_ _lolcathost_enitsda" src="https://user-images.githubusercontent.com/4076390/49292671-36762780-f4ae-11e8-8f56-3ee11bccfa2a.png">

**Comment by dsecuma** [comment]
Se hizo un collectstatic a /static y ahora lo sirve nginx con 

```
location /static/ {
       alias   /home/cybercamp/enitsda/static/;
    }
```

¿Sigue siendo esto erroneo para dejarlo en "produccion"?
