### ISSUE TITLE
Excepciones omitidas

### ISSUE THREAD

**Issue by cr0hn** [lolcathost/enitsda#9]
Es una mala práctica capturar una excepción y no notificar del fallo de alguna forma. De esta maneara no seremos capaces de detectar si la aplicación está teniendo errores o no:

<img width="630" alt="enitsda_enitsda_deauth_py_at_master_ _lolcathost_enitsda" src="https://user-images.githubusercontent.com/4076390/49294503-670c9000-f4b3-11e8-8ce3-69731e734494.png">

**Comment by dsecuma** [comment]
Asociado a commit 4061dbb1a70479bcd6b61be9519b104001c119ac
